### PR TITLE
Fixes on creating a wallet with coin type level key.

### PR DESCRIPTION
**Pull request by computerpoet**

### CODE REVIEW

**Comment by HashEngineering** [comment]
I will review this.

**Comment by HashEngineering** [comment]
**Adding the Creation Date to every key**
Currently bitcoinj works with having the root key storing the creation time. I would think we can do the same. The root key in this case is the parent key listed above which is the coin type level key.

Why do you need to record the creation time on every key?

**Comment by computerpoet** [comment]
@HashEngineering 

> Adding the Creation Date to every key
> Currently bitcoinj works with having the root key storing the creation time. I would think we can do the same. The root key in this case is the parent key listed above which is the coin type level key.
> 
> Why do you need to record the creation time on every key?

That is not what i observed, without my changes, it scans from 2012 and not the creation time of the root key.

**Comment by HashEngineering** [comment]
Ok, thanks for that answer.  In my testing I will verify your findings and make sure all the unit tests are working as well as my own test that I was using.  I should have testing finished by tomorrow.

It's possible that the documentation is wrong regarding the creation time only being required in the parent key.  There may be another solution than storing the creation time in every key.

**Comment by computerpoet** [comment]
@HashEngineering Could you point to where have you seen in the documentation that "the creation time only being required in the parent key." ?

**Comment by HashEngineering** [comment]
https://github.com/HashEngineering/bitcoinj/pull/3/files#diff-b5705bce28d8b7c33a69b5c5c42ca901L840

This link is the source of the comment stating as much.  This is probably true for a seed (and it is true based on my experience), but we are doing keys.

**Comment by HashEngineering** [comment]
Here is another link:  `DeterminisiticKey.getCreationTimeSeconds()`
https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/crypto/DeterministicKey.java#L566

If a key has a parent, then it will use the parent's creation time.

If this actually works, then when we import a key into bitcoinj, then we need to set the creationTime in the key before.  Or we need to include the creationTime as an argument in the import function.

Here is an example of a import method that requires that the masterKey have its creationTime set before calling fromMasterKey.
https://github.com/HashEngineering/bitcoinj/blob/importhdkey/core/src/main/java/org/bitcoinj/wallet/Wallet.java#L352
```
    /**
     * Creates a wallet that tracks payments to and from the HD key hierarchy rooted by the given spending key. A
     * spending key corresponds to account zero in the recommended BIP32 key hierarchy.  This wallet can also spend.
     */
    public static Wallet fromMasterKey(NetworkParameters params, DeterministicKey masterKey, int accountNumber) {
        return new Wallet(params, new KeyChainGroup(params, new DeterministicKey(ImmutableList.<ChildNumber>of(new ChildNumber(accountNumber, true)),masterKey.getChainCode(), masterKey.getPrivKey(), masterKey)));
    }
```

Here is an example where the creationTime is included as an argument:
https://github.com/HashEngineering/bitcoinj/blob/importhdkey/core/src/main/java/org/bitcoinj/wallet/Wallet.java#L342
```
    public static Wallet fromSpendingKeyB58(NetworkParameters params, String spendingKeyB58, long creationTimeSeconds) {
        final DeterministicKey spendKey = DeterministicKey.deserializeB58(null, spendingKeyB58, params);
        spendKey.setCreationTimeSeconds(creationTimeSeconds);
        return fromSpendingKey(params, spendKey);
    }
```

**Comment by computerpoet** [comment]
```kotlin
val coinTypeKey = DeterministicKey.deserializeB58(spendingKeyB58, Constants.NETWORK_PARAMETERS)
coinTypeKey.creationTimeSeconds = creationTimeSeconds
val walletAccount = Wallet.fromMasterKey(Constants.NETWORK_PARAMETERS, coinTypeKey, accountIndex)
```

This is the code we are using right now. Without my changes to the creation time, checkpoints are not working.

**Comment by HashEngineering** [comment]
Thanks for the feedback.  Some of these commits were used.

**Pull request closed without merging**
