### PR TITLE
Fix creating a wallet with coin type level key and a custom account path.

### PR DESCRIPTION
**Pull request by computerpoet**

### CODE REVIEW

**Comment by HashEngineering** [comment]
I started my review process of this code.  Based on my understanding of bitcoinj some of these changes are not necessary, but one is.

While the main purpose of this branch (importhdkey) is to allow importing, watching, spending of a "coin type level key" that is a BIP44 (m/44'/0'/<account>), bitcoinj doesn't need to know if it is m/<account> or m/44'/0'/<account>.  However it will need to know the <account>.  This will be the parent key of all other keys (internal, external).

**The necessary change**:  Add the creation time to account key that is added.  This was previously missing, though I realize that my unit tests (spendingChain and spendingChainAccountTwo) added the creation time.  The creation time allows for resetting the blockchain sooner than at the genesis block.  The parent key will need its creation time set via `spend` or other top level parent key creation method.

**Adding the Account Path**
I don't see this as a necessary change, because the DeterministicKey has a path or child number already if it is created from an xprv.

**Adding the Creation Date to every key**
Currently bitcoinj works with having the root key storing the creation time.  I would think we can do the same.  The root key in this case is the parent key listed above which is the coin type level key.

@DaLN Let me know why your use case or software system requires all of these changes.

Due to these changes, 5 tests fail.  Three are due to the inclusion of the creation seed on every key.  Two fail for other reasons.  I can help fix these after we figure out the changes that are required.

I noticed that my AccountTwoChain class in the unit test actually creates an 1H account, so I will fix that.

**Comment by computerpoet** [comment]
@HashEngineering Thanks for your comments, i initially went the wrong way to make this code work for us so i started from scratch to make sure to add exactly what was necessary.

The issue why i added the account path is that 
```java
public DeterministicKeyChain(DeterministicKey key, boolean isFollowing, boolean isWatching) {
        if(isWatching)
            checkArgument(key.isPubKeyOnly(), "Private subtrees not currently supported: if you got this key from DKC.getWatchingKey() then use .dropPrivate().dropParent() on it first.");
        else
            checkArgument(key.hasPrivKey(), "Private subtrees are required.");
        checkArgument(isWatching ? true : !isFollowing, "Cannot follow a key that is not watched");
        checkArgument(key.getPath().size() == getAccountPath().size(), "You can only watch an account key currently");
```
In that last line accountPath is null so it returns ACCOUNT_ZERO_PATH which has a size of 1, while the key has a size of 2 (1H, 0H).

I can go two ways about solving this, deleting this check or providing the accountPath to the DeterministicKeyChain.

**Comment by computerpoet** [comment]
@HashEngineering I made a more concise PR there https://github.com/HashEngineering/bitcoinj/pull/2

**Comment by HashEngineering** [comment]
I will review it over the next few days.

**Pull request closed without merging**
